current_version: "201911.2.0"
strategy:
  name: "calver"
  part: "auto"
  version_format: "YYYYMM.MINOR.MICRO"
commit:
  author: "Jill San Luis <jill.devs@gmail.com>"
tag:
  apply: True
  format: "v{version}"
auto_remote_push: True
tracked_files:
  - README.md
  - sample/VERSION
